### ISSUE TITLE
Improve accessibility on forms 

### ISSUE THREAD

**Issue by GyD** [openfed/openfed8#105]
Hello,

There is a small accessibility issue with ID generated by drupal/core on forms.
Drupal duplicates ID between forms and that cause error in W3C report ( https://www.w3.org/WAI/WCAG21/Understanding/parsing )

That mean for every projects we are working on, we have to apply a patch to fix this issue. 
Do you think this issue could be solved in openfed8 directly ? This way it's not forgotten in the development process.

You can read more about this in this related issue: https://www.drupal.org/project/drupal/issues/1831560
Patch we are currently using for our D8 projects: https://www.drupal.org/files/issues/2019-10-11/1831560-61.patch

Thanks a lot

**Comment by GyD** [comment]
Additional note:
- It's maybe not a issue in Drupal 8.9 : https://www.drupal.org/project/drupal/issues/3169918

**Comment by rutiolma** [comment]
The patch mentioned was cherry picked to Drupal 8.9: https://www.drupal.org/project/drupal/issues/1831560#comment-13650752
This introduced a new issue as stated on https://www.drupal.org/project/drupal/issues/3169918 so any sites relying on blockID for css/js will be broken.

In any case, on what concerns this issue, it has been fixed with new core version.
