### ISSUE TITLE
Ctools plugin for contextually rendering menus?

### ISSUE THREAD

**Issue by j1mb0b** [openfed/openfed8#34]
This is more of a "should we" type question. I'm having to repetitively embed each menu block per language into my context / panels variant(s). This is because there is a separate menu block per language. One idea is to develop a custom ctools plugin for OpenFed that allows the end user to embed a single menu block which renders the correct menu contextual to the current language, limited to a configurable set of menu's exposed as initial configuration within the plugin.

The other potential approach is to use a view block but since menus are not yet exposed to views its not clear on how this can be achieved.

**Comment by rutiolma** [comment]
The problem with rendering menu blocks based on context is that due to the way menus are handled in Openfed (with menu_link) we don't really have a relationship between menus (so a Main Menu EN is not related in any way with Main Menu FR). As such, menu blocks will always have to be placed one by one.
Closing this issue.
