### ISSUE TITLE
Integrate "Fontawesome" to OpenFed

### ISSUE THREAD

**Issue by InPhoenityOld** [openfed/openfed8#54]
Based on our internal QA process, we try to use more and more FontAwesome for a lot of things. Including this module would allow to even use it for fields (with a nice display) so it can be nice to be integrated.

https://www.drupal.org/project/fontawesome

What do you think ?

**Comment by rutiolma** [comment]
Indeed fontawesome is needed for Kiso, but Kiso already includes this library.
The only situation where Fontawesome module is necessary is if we need to include "icons" on a project but Fontello is better at that since it allows to add our own custom icon sets.

IMO, if fontawesome can include only the necessary libraries (as needed by Kiso) and doesn't add any other overheads, we can include the module and drop the library from kiso.

To be investigated.
Postponing it to Openfed 8.7.

**Comment by rutiolma** [comment]
After checking with the frontend team I see that kiso requires only one file from fontawesome and doesn't add any other overheads so it's better to keep it like that.
About adding an icon module, like fontello, it's not a common request for now so we'll postpone it. This issue can be reopened if the situation changes.
