### ISSUE TITLE
Implement "Archived" state for moderation

### ISSUE THREAD

**Issue by stefanruijsenaars** [openfed/openfed8#7]
Currently it is not possible to unpublish documents, we need to create new transitions published -> archived, archived -> draft, archived -> published.

**Comment by bdeclerc** [comment]
Wondering if the "Trash" module wouldn't be a better solution - after all, it's possible to unpublish by going into "Draft" and having a back-end archive of old content isn't an automatic functional requirement for many customers.

**Comment by rutiolma** [comment]
Actually going to Draft doesn't unpublish since there'll be a Published revision. Yes, this could be easy done using the "moderation" page, but we don't have that yet on D8. It's also possible to unpublish content using the bulk actions on content but it just seems more intuitive using an Archive state.

The "Archive" state is a default d8 state used to unpublish content. Before rc1 we we're removing it but, right now, this seems to be the best solution to unpublish content.

**Comment by bdeclerc** [comment]
Yeah, keep it in – it makes a lot of sense and at any rate “Trash” isn’t really production-ready IMHO (due to dependencies on Content Moderation, but they’re working on eliminating those)

Bart Declercq
Application Architect WCM
Digitale Transformatie

[cid:image003.jpg@01D29353.79967D80]FOD Beleid en Ondersteuning
WTCIII - Simon Bolivarlaan 30
1000 Brussel
t +32 (0) 2 212 96 59 • gsm +32 (0)475 46 02 58
bart.declercq@fedict.be• www.bosa.be<http://www.bosa.be/>
