### ISSUE TITLE
Administration Theme for Openfed

### ISSUE THREAD

**Issue by rutiolma** [openfed/openfed8#91]
We are facing some issues on some projects where we have the necessity to create custom styles for certain administration elements and it's not always easy to create patches for core/contrib themes to fix contrib modules issues.

I know that we've been avoiding the creation of a custom administration theme but what do you think about creating a custom admin theme, extending adminimal, which the solo purpose is to give us more freedom to create fixes for contrib modules we are using (I'm thinking about custom and localized CSS only, no twig templates or functions)

Example: When using views_tree or multiselect modules, the administration form looks "broken" due to the way Drupal is rendering these elements. In this case, the patch should be done on core "Classy" theme, and I believe it will be difficult to get it approved.

What do you think?

**Comment by bdeclerc** [comment]
Alright, I've considered this and I agree that a custom theme with as primary goal "fixing" issues due to integrating fixes for UI issues with contrib modules is the best approach. I do think we need to evaluate each time if the issue is due to actual bugs in the contrib module or due to the way we use it in combination with adminimal and attempt to provide bugfixes to the community where possible.

But we also need to look to the future - so we need to start looking at https://www.drupal.org/project/claro

Clearly that's not yet ready, but I think on our roadmap we should probably consider implementing it when we move to Drupal 9.x (provided that it gets sufficiently stabilized by then).

So IMHO two parallel tracks: custom theme based on adminimal for Openfed8, but use Claro for Openfed9, potentially with the same formula of having a custom theme to handle any issues, though there should be fewer of them as most modules will likely start working well with Claro as it becomes more popular anyway.

I'm not seeing a lot of movement on making Adminimal Drupal 9 compatible yet (but that might also mean there's not a lot of work to be done...)

**Comment by rutiolma** [comment]
This seems to be the best option for me as well.
Our custom theme, in order to do the adjustments we want/need, is easily convertible to Claro since it will just update some styles.

The issues we had with multiselect and views_tree are also present on Claro and, although we could create a patch, I'm not really sure if we need to patch the modules or Adminimal (or Drupal core Classy base theme and other administration themes like Claro)

We'll move on with the implementation of a openfed_admin theme

**Comment by rutiolma** [comment]
Theme created and set as default.
